title: home
description: "Academic website"
url: "https://wiernik.github.io"  
baseurl: "/wierniksarea"               

theme: minima                      
plugins:
  - jekyll-feed
  - jekyll-seo-tag
