title: Lydia Wiernik
description: Academic website
url: https://wiernik.github.io/wierniksarea
baseurl: ""                        

theme: minima                      
plugins:
  - jekyll-feed
  - jekyll-seo-tag
